package com.app.mlm.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.app.mlm.bean.GoodsInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GOODS_INFO".
*/
public class GoodsInfoDao extends AbstractDao<GoodsInfo, Long> {

    public static final String TABLENAME = "GOODS_INFO";

    /**
     * Properties of entity GoodsInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MdseId = new Property(1, int.class, "mdseId", false, "MDSE_ID");
        public final static Property MdsePrice = new Property(2, String.class, "mdsePrice", false, "MDSE_PRICE");
        public final static Property MdseName = new Property(3, String.class, "mdseName", false, "MDSE_NAME");
        public final static Property MdseUrl = new Property(4, String.class, "mdseUrl", false, "MDSE_URL");
        public final static Property ClCode = new Property(5, String.class, "clCode", false, "CL_CODE");
        public final static Property ClCapacity = new Property(6, int.class, "clCapacity", false, "CL_CAPACITY");
        public final static Property ClcCapacity = new Property(7, int.class, "clcCapacity", false, "CLC_CAPACITY");
        public final static Property GamePrice = new Property(8, String.class, "gamePrice", false, "GAME_PRICE");
        public final static Property GameTimeStart = new Property(9, String.class, "gameTimeStart", false, "GAME_TIME_START");
        public final static Property GameTimeEnd = new Property(10, String.class, "gameTimeEnd", false, "GAME_TIME_END");
        public final static Property Position = new Property(11, int.class, "position", false, "POSITION");
    }


    public GoodsInfoDao(DaoConfig config) {
        super(config);
    }
    
    public GoodsInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GOODS_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MDSE_ID\" INTEGER NOT NULL ," + // 1: mdseId
                "\"MDSE_PRICE\" TEXT," + // 2: mdsePrice
                "\"MDSE_NAME\" TEXT," + // 3: mdseName
                "\"MDSE_URL\" TEXT," + // 4: mdseUrl
                "\"CL_CODE\" TEXT," + // 5: clCode
                "\"CL_CAPACITY\" INTEGER NOT NULL ," + // 6: clCapacity
                "\"CLC_CAPACITY\" INTEGER NOT NULL ," + // 7: clcCapacity
                "\"GAME_PRICE\" TEXT," + // 8: gamePrice
                "\"GAME_TIME_START\" TEXT," + // 9: gameTimeStart
                "\"GAME_TIME_END\" TEXT," + // 10: gameTimeEnd
                "\"POSITION\" INTEGER NOT NULL );"); // 11: position
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GOODS_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GoodsInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMdseId());
 
        String mdsePrice = entity.getMdsePrice();
        if (mdsePrice != null) {
            stmt.bindString(3, mdsePrice);
        }
 
        String mdseName = entity.getMdseName();
        if (mdseName != null) {
            stmt.bindString(4, mdseName);
        }
 
        String mdseUrl = entity.getMdseUrl();
        if (mdseUrl != null) {
            stmt.bindString(5, mdseUrl);
        }
 
        String clCode = entity.getClCode();
        if (clCode != null) {
            stmt.bindString(6, clCode);
        }
        stmt.bindLong(7, entity.getClCapacity());
        stmt.bindLong(8, entity.getClcCapacity());
 
        String gamePrice = entity.getGamePrice();
        if (gamePrice != null) {
            stmt.bindString(9, gamePrice);
        }
 
        String gameTimeStart = entity.getGameTimeStart();
        if (gameTimeStart != null) {
            stmt.bindString(10, gameTimeStart);
        }
 
        String gameTimeEnd = entity.getGameTimeEnd();
        if (gameTimeEnd != null) {
            stmt.bindString(11, gameTimeEnd);
        }
        stmt.bindLong(12, entity.getPosition());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GoodsInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMdseId());
 
        String mdsePrice = entity.getMdsePrice();
        if (mdsePrice != null) {
            stmt.bindString(3, mdsePrice);
        }
 
        String mdseName = entity.getMdseName();
        if (mdseName != null) {
            stmt.bindString(4, mdseName);
        }
 
        String mdseUrl = entity.getMdseUrl();
        if (mdseUrl != null) {
            stmt.bindString(5, mdseUrl);
        }
 
        String clCode = entity.getClCode();
        if (clCode != null) {
            stmt.bindString(6, clCode);
        }
        stmt.bindLong(7, entity.getClCapacity());
        stmt.bindLong(8, entity.getClcCapacity());
 
        String gamePrice = entity.getGamePrice();
        if (gamePrice != null) {
            stmt.bindString(9, gamePrice);
        }
 
        String gameTimeStart = entity.getGameTimeStart();
        if (gameTimeStart != null) {
            stmt.bindString(10, gameTimeStart);
        }
 
        String gameTimeEnd = entity.getGameTimeEnd();
        if (gameTimeEnd != null) {
            stmt.bindString(11, gameTimeEnd);
        }
        stmt.bindLong(12, entity.getPosition());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GoodsInfo readEntity(Cursor cursor, int offset) {
        GoodsInfo entity = new GoodsInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // mdseId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mdsePrice
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mdseName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // mdseUrl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // clCode
            cursor.getInt(offset + 6), // clCapacity
            cursor.getInt(offset + 7), // clcCapacity
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // gamePrice
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // gameTimeStart
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // gameTimeEnd
            cursor.getInt(offset + 11) // position
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GoodsInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMdseId(cursor.getInt(offset + 1));
        entity.setMdsePrice(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMdseName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMdseUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setClCode(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setClCapacity(cursor.getInt(offset + 6));
        entity.setClcCapacity(cursor.getInt(offset + 7));
        entity.setGamePrice(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setGameTimeStart(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setGameTimeEnd(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setPosition(cursor.getInt(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GoodsInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GoodsInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GoodsInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
